### ISSUE TITLE
Crash with "The Lord of the Rings Mod: Legacy"

### ISSUE THREAD

**Issue by ootwclyhe** [LegacyModdingMC/UniMixins#13]
mc version:1.7.10 
forge version:7.99.40.1614 
java version:1.8.0_362

the crash occurs after i add the LotR into the mods folder

https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-legacy
https://github.com/FalsePattern/EndlessIDs
https://github.com/FalsePattern/FalsePatternLib

[fml-server-latest.log](https://github.com/LegacyModdingMC/UniMixins/files/12394563/fml-server-latest.log)

`[17:09:25] [main/INFO] [mixin/]: Instancing error handler class io.github.legacymoddingmc.unimixins.compat.MixinErrorHandler
[17:09:25] [main/FATAL] [mixin/]: Mixin prepare for mod endlessids failed preparing common.biome.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin in mixins.endlessids.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException The specified mixin 'com.falsepattern.endlessids.mixin.mixins.common.biome.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'com.falsepattern.endlessids.mixin.mixins.common.biome.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:865) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:797) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) [+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) [?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) [?:1.8.0_362]
	at java.lang.Class.forName0(Native Method) [?:1.8.0_362]
	at java.lang.Class.forName(Class.java:348) [?:1.8.0_362]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge1.7.10-universal.jar:?]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'com.falsepattern.endlessids.mixin.mixins.common.biome.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1314) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:858) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	... 23 more
[17:09:25] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.server.MinecraftServer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_362]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_362]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_362]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge1.7.10-universal.jar:?]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge1.7.10-universal.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.endlessids.json:common.biome.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin from mod endlessids] from phase [DEFAULT] in config [mixins.endlessids.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:570) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'com.falsepattern.endlessids.mixin.mixins.common.biome.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:865) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:797) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'com.falsepattern.endlessids.mixin.mixins.common.biome.lotr.LOTRPacketBiomeVariantsWatchHandlerMixin' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1314) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:858) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:797) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) ~[+unimixins-all-1.7.10-0.1.11.jar:0.12.2+mixin.0.8.5]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	... 12 more
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:101)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:987)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17:09:25] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 6 more
[fml-server-latest.log](https://github.com/LegacyModdingMC/UniMixins/files/12394442/fml-server-latest.log)
`

**Comment by ootwclyhe** [comment]
[fml-server-latest.log](https://github.com/LegacyModdingMC/UniMixins/files/12394539/fml-server-latest.log)

**Comment by ootwclyhe** [comment]
Solved,this caused by endlessid and lotr conflict，just set config/endlessids.cfg/extendBiome=false
