### ISSUE TITLE
Conflict with CustomNPC+ 

### ISSUE THREAD

**Issue by TechDurka** [LegacyModdingMC/UniMixins#25]
**Error initialising mixin config customnpcs.mixins.json**
**Caused by: java.lang.IllegalArgumentException: The specified resource 'customnpcs.mixins.json' was invalid or could not be read**

[mixins.customnpcs.json](https://github.com/LegacyModdingMC/UniMixins/files/14790923/mixins.customnpcs.json)

`Exception in thread "main" [15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config customnpcs.mixins.json
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:269)
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:46)
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.prepare(MixinPlatformManager.java:172)
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.MixinBootstrap.doInit(MixinBootstrap.java:196)
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.launch.MixinTweaker.acceptOptions(MixinTweaker.java:55)`

`[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.IllegalArgumentException: The specified resource 'customnpcs.mixins.json' was invalid or could not be read
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
[15:57:27] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 12 more`

[CustomNPC+ on curseforge](https://www.curseforge.com/minecraft/mc-mods/customnpc-plus)

**Comment by makamys** [comment]
This doesn't look like UniMixins' fault, CustomNPC+ is looking for the wrong mixin json filename (it should be `mixins.customnpcs.json`, but it's `customnpcs.mixins.json`).

I'm guessing you got this in a dev environment following the instructions in the readme, which [still wrongly say](https://github.com/KAMKEEL/CustomNPC-Plus/blob/220595bf31a4e682cb9a3c264f49e66e6d736e7e/README.md#cloning--compiling--building) `customnpcs.mixins.json` should be used, since it wasn't updated when the mod got refactored to use RFG. In that case this is an issue with CustomNPC's documentation. Anyway, that should be discussed with them, not here.
